server:
  port: 8080

---
spring:
  profiles: dev

  datasource:
    url: jdbc:h2:mem:dev
    driverClassName: org.h2.Driver
    username: sa
    password:
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path=: /h2_console

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: true
    ddl-auto: update

  jwt:
    secret: hash-key-dev
---
spring:
  profiles: prod

  datasource:
    url: jdbc:h2:mem:prod
    driverClassName: org.h2.Driver
    username: sa
    password:
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path=: /h2_console

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: true
    ddl-auto: update

  jwt:
    secret: hash-key-prod